doctrine:
    dbal:
        # add own ip to access hosts in direct admin
        host: 'localhost'
        port: '3306'
        dbname: 'u80913p75654_main'
        user: 'u80913p75654_main'
        password: 'cm!$awO0Y19W'
        charset: UTF8

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
